# -*- coding: utf-8 -*-
"""halo_dunia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n4GMcg59q-nvZmB_dpAHkR5W7xQD5JHM
"""

print('Halo Dunia !')
print('Belajar AI !')